prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelm: false
    serviceMonitorSelector: {}
    retention: 7d

grafana:
  adminPassword: admin
  defaultDashboardsEnabled: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'performance'
        orgId: 1
        folder: 'Performance'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/performance
  dashboards:
    performance:
      performance-dashboard:
        file: dashboards/performance-dashboard.json